piscine_django/day04/day04/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ex00/', include('ex00.urls')),
    path('ex01/', include('ex01.urls')),
    path('ex02/', include('ex02.urls')),
    path('ex03/', include('ex03.urls')),
    path('admin/', admin.site.urls),
]

piscine_django/day04/ex00/urls.py
from django.urls import path

from . import views

app_name = 'ex00'
urlpatterns = [
    # ex: /polls/
    path('', views.markdown, name='index'),
]

piscine_django/day04/ex01/urls.py
from django.urls import path
# from django.conf.urls.static import static
from . import views

app_name = 'ex01'
urlpatterns = [
    # ex: /polls/
    path('django_description', views.django_description, name='django_description'),
    path('display_process_static_page', views.display_process_static_page, name='display_process_static_page'),
    path('template_engine', views.template_engine, name='template_engine'),
]

piscine_django/day04/ex02/urls.py
from django.urls import path
# from django.conf.urls.static import static
from . import views

app_name = 'ex02'
urlpatterns = [
    # ex: /polls/
    path('form_exercice', views.form_exercice, name='form_exercice'),
]

piscine_django/day04/ex03/urls.py
from django.urls import path
# from django.conf.urls.static import static
from . import views

app_name = 'ex03'
urlpatterns = [
    # ex: /polls/
    path('tab_exercice', views.tab_exercice, name='tab_exercice'),
]

piscine_django/day04/ex00/models.py
from django.db import models

# Create your models here.

piscine_django/day04/ex01/models.py
from django.db import models

# Create your models here.

piscine_django/day04/ex02/models.py
from django.db import models
from django import forms

# Create your models here.


class MessageForm(forms.Form):
    message = forms.CharField(label='message', max_length=300)

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields['message'].widget.attrs['placeholder'] = 'Votre message'

piscine_django/day04/ex03/models.py
from django.db import models

# Create your models here.

piscine_django/day04/ex00/views.py
from django.shortcuts import render
import requests
from bs4 import BeautifulSoup

def markdown(request):
    # link = "https://en.m.wikipedia.org/wiki/Markdown"
    # print("lien : ", link)
    # response = requests.get(link)
    # if response.status_code != 200: 
    #     print("Erreur", str(response.status_code))
    #     exit()
    # else:
    #     response = response.text
    # soup = BeautifulSoup(response, features="html.parser")
    # # print("ici")
    # soup.prettify()
    # body = soup.find('body')
    # myfile = open("./ex00/templates/markdown.html", 'w')
    # myfile.write(str(body))
    # myfile.close()
    return render(request, 'ex00/index.html')


if __name__ == "__main__":
    markdown(1)

piscine_django/day04/ex01/views.py
from django.shortcuts import render
from django.template import loader
import requests
from bs4 import BeautifulSoup


def get_info_from_wikipedia(page):
    link = "https://en.wikipedia.org/wiki/" + page
    print("lien : ", link)
    # https://en.m.wikipedia.org/wiki/Django_(web_framework)
    response = requests.get(link) 
    if response.status_code != 200: 
        print("Erreur", str(response.status_code))
        exit()
    else:
        response = response.text
    soup = BeautifulSoup(response, features="html.parser")
    soup.prettify()

    # body = soup.find('body')
    # myfile = open("./templates/test.html", 'w')
    # myfile.write(str(body))
    # myfile.close()

    #paragraphes d'intro
    div = soup.find("div", {"class": "shortdescription nomobile noexcerpt noprint searchaux"}, recursive=True)
    for paragraphe in div:
        print(paragraphe.text)
    # print(div.text)
    exit(0)

    #On recherche le premier (vrai) paragraphe
    for paragraphe in paragraphes:
        try:
            paragraphe['class'][0]
        except:
            try:
                gras = paragraphe.findChildren("b" , recursive=True)
                gras[0]
                # print(gras[0])
                break
            except:
                continue

# Create your views here.
def django_description(request):
    return render(request, 'ex01/django_description.html')

def display_process_static_page(request):
    return render(request, 'ex01/display_process_static_page.html')

def template_engine(request):
    return render(request, 'ex01/template_engine.html')

if __name__ == "__main__":
    get_info_from_wikipedia("Django_(web_framework)")

piscine_django/day04/ex02/views.py
from django.shortcuts import render, redirect
from .models import MessageForm
from datetime import datetime
from django.urls import reverse
from ex02 import views
from django.shortcuts import redirect


# Create your views here.
def form_exercice(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = MessageForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # inscrire les entrées du form dans le fichier log
            message = form.cleaned_data['message']
            date = datetime.utcnow().strftime('%d/%m/%Y %H:%M:%S')
            log = open("message.log", "a")
            log.write(str(date) + " : " + message + "\n")
            log.close()

            # return redirect('/ex02/form_exercice', request)
            return redirect('ex02:form_exercice')
    

    # if a GET (or any other method) we'll create a blank form
    else:
        form = MessageForm()
        # on recupere les messages dans le fichier log
        log = open("message.log", "r")
        messages = log.readlines()
        for message in messages:
            message = message[22:]
        log.close()

        return render(request, 'ex02/form_exercice.html', {
            'form': form,
            'messages': messages,
            })

# if __name__ == "__main__":
#     log = open("message.log", "r")
#     messages = log.readlines()
#     for message in messages:
#         message = message[22:]
#     print(messages)
#     log.close()

piscine_django/day04/ex03/views.py
from django.shortcuts import render
import colorsys


def get_nuances():
    colors = [(x * 1.0 / 100) for x in range(2, 102, 2)]
    return colors

# Create your views here.
def tab_exercice(request):
    colors = get_nuances()
    return render(request, 'ex03/tab_exercice.html', {'colors': colors})

if __name__ == "__main__":
    tab_color = get_nuances()
    print(tab_color)

piscine_django/day04/day04/templates/day04/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <title>
            {% block title %}
            {% endblock %}
        </title>
        {% block style %}
            <link rel="stylesheet" type="text/css" href="{% static 'day04/style.css' %}">
        {% endblock %}
    </head>
  
    <body>
        <div class="text-center"> 
            <a href="{% url 'ex01:django_description' %}" style="text-decoration: none; color:black">
            <h1>Piscine Django</a></h1>
        </div>
        {% include 'nav.html' %}
        {% block content %}
        {% endblock %}
    </body>
</html>

piscine_django/day04/day04/templates/day04/nav.html
<div id="navbar">
    <div class="container page-header sticky-top">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'ex00:index' %}">Ex00 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Ex01
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="{% url 'ex01:django_description' %}">Django, Framework web.</a>
                      <a class="dropdown-item" href="{% url 'ex01:display_process_static_page' %}">Processus d'affichage d'une page statique.</a>
                      <a class="dropdown-item" href="{% url 'ex01:template_engine' %}">Moteur de template.</a>
                  </div>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'ex02:form_exercice' %}">Ex02 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'ex03:tab_exercice' %}">Ex03 <span class="sr-only">(current)</span></a>
                </li>
              </ul>
            </div>
          </nav>
    </div>
</div>

piscine_django/day04/ex00/templates/ex00/index.html
{% extends 'base.html' %}

{% block title %}Ex00 : Markdown Cheatsheet{% endblock %}
{% block style %}{% endblock %}
{% block content %}
  <div class="row d-flex justify-content-center">
    <div class="col-md-10">
      <div style="border: 3px solid grey; overflow: hidden; margin: 50px;">
        <iframe src="https://en.m.wikipedia.org/wiki/Markdown" width="100%" height="1550px"></iframe>
      </div>
    </div>
  </div>
  
{% endblock %}

piscine_django/day04/ex01/templates/ex01/base.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'ex01/style1.css' %}">
{% endblock %}

piscine_django/day04/ex01/templates/ex01/display_process_static_page.html
{% extends 'ex01/base.html' %}

{% block title %}Ex01 : Processus d'affichage d'une page statique.{% endblock %}
{% block content %}
    <div class="row d-flex justify-content-center mt-5">
        <div class="col-md-6">
            <p>Une page web statique est une page web dont le contenu ne varie pas en fonction des caractéristiques de la demande, c'est-à-dire qu'à un moment donné tous les internautes qui demandent la page reçoivent le même contenu.</p>
            <p>À l'inverse, une page web dynamique est générée à la demande et son contenu varie en fonction des caractéristiques de la demande (heure, adresse IP de l'ordinateur du demandeur, formulaire rempli par le demandeur, etc.) qui ne sont connues qu'au moment de sa consultation.</p>
            <p>Lors de la consultation d'une page web statique, un serveur HTTP envoie le contenu du fichier dans lequel le contenu de la page est enregistré.</p>
            <p>Lors de la consultation d'une page web dynamique, un serveur HTTP transmet la requête à un logiciel qui génère le contenu de la page. Les logiciels générant des pages web dynamiques sont fréquemment écrits avec les langages PHP, JavaServer Pages (JSP) ou Active Server Pages (ASP). Les pages ou sites web statiques se font de plus en plus rares. Une page web statique n'est programmée qu'avec les langages de programmation de base : HTML et (facultatif) CSS; à la différence des pages dynamiques.</p>
        </div>
    </div>
{% endblock %}

piscine_django/day04/ex01/templates/ex01/django_description.html
{% extends 'ex01/base.html' %}

{% block title %}Ex01 : Django, Framework web.{% endblock %}
{% block content %}
    {% comment %} {{ STATIC_URL }} {% endcomment %}
    <div class="row d-flex justify-content-center mt-5">
        <div class="col-md-6">
            <p>Django (/ˈdʒæŋɡoʊ/ JANG-goh; stylised as django) is a Python-based free and open-source web framework, 
            which follows the model-template-view (MTV) architectural pattern. It is maintained by the Django 
            Software Foundation (DSF), an independent organization established as a 501 non-profit. </p>
            <p>Django's primary goal is to ease the creation of complex, database-driven websites. The framework emphasizes reusability and "pluggability" of components, less code, low coupling, rapid development, and the principle of don't repeat yourself. Python is used throughout, even for settings files and data models. Django also provides an optional administrative create, read, update and delete interface that is generated dynamically through introspection and configured via admin models.</p>
            <p>Some well-known sites that use Django include the Public Broadcasting Service, Instagram, Mozilla, The Washington Times, Disqus, Bitbucket, and Nextdoor.</p>
        </div>
    </div>
{% endblock %}

piscine_django/day04/ex01/templates/ex01/template_engine.html
{% extends 'ex01/base.html' %}

{% block title %}Ex01 : Django, Framework web.{% endblock %}
{% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'ex01/style2.css' %}" />
{% endblock %}

{% block content %}
{% comment %} 
    verbatim allow us to write twig code without being interprated  
{% endcomment %}
{% verbatim myblock %} 
<div class="row d-flex justify-content-center mt-5">
    <h1>Le langage de template de Django</h1>
</div>
<div class="row d-flex justify-content-center mt-5"></div>
    <div class="col-md-10">
        <br>
        <h2>Template :</h2>
        <br>
        C'est la vue qui se charge de transmettre l'information de la requête au template, puis de retourner le HTML généré au client.
        <br>

        <br>
        <h2>conditions : {% if %}</h2>
        <br>
        Tout comme en Python, il est possible d'exécuter des conditions dans votre template selon la valeur des variables passées au template :
        <br>

        <br>
        Bonjour
        <br>
        {% if sexe == "Femme" %}
        <br>
        Madame
        <br>
        {% else %}
        <br>
        Monsieur
        <br>
        {% endif %} !
        <br>

        <br>
        Ici, en fonction du contenu de la variable sexe, l'utilisateur ne verra pas le même texte à l'écran.
        <br>
        Ce template est similaire au code HTML généré par la vue suivante :
        <br>
        <br>
            sexe = "Femme"
        <br>
            html = "Bonjour "
        <br>
            if sexe == "Femme":
        <br>
                html += "Madame"
        <br>
            else:
        <br>
                html += "Monsieur"
        <br>
            html += " !"
        <br>
            return HttpResponse(html)
        <br>

        <br>
        La séparation entre vue et template simplifie grandement les choses, et permet une plus grande lisibilité que lorsque le code HTML est écrit directement dans la vue !
        <br>

        <br>
        Il est également possible d'utiliser les structures if, elif, else de la même façon :
        <br>

        <br>
        {% if age > 25 %}
        <br>
            Bienvenue Monsieur, passez un excellent moment dans nos locaux.
        <br>
        {% elif age > 16 %}
        <br>
            Vas-y, tu peux passer.
        <br>
        {% else %}
        <br>
            Tu ne peux pas rentrer petit, tu es trop jeune !
        <br>
        {% endif %}
        <br>

        <br>

        <br>
        <h2>for:</h2>
        <br>
        Tout comme les conditions, le moteur de templates de Django permet l'utilisation de la boucle for, similaire à celle de Python. Admettons que nous possédions dans notre vue un tableau de couleurs définies en Python :
        <br>
        couleurs = ['rouge', 'orange', 'jaune', 'vert', 'bleu', 'indigo', 'violet']
        <br>
        Nous décidons dès lors d'afficher cette liste dans notre template grâce à la syntaxe {% for %} suivante :
        <br>
        Les couleurs de l'arc-en-ciel sont :
        <br>

        <br>
        {% for couleur in couleurs %}
        <br>
            {{ couleur }}
        <br>
        {% endfor %}
        <br>

        <br>
        Avec ce template, le moteur va itérer la liste (cela fonctionne avec n'importe quel autre type itérable), remplacer la variable couleur par l'élément actuel de l'itération et générer le code compris entre {% for %} et {% endfor %} pour chaque élément de la liste.
        <br>
        Il est aussi possible de parcourir un dictionnaire, en passant par la directive {% for cle, valeur in dictionnaire.items %} :
        <br>

        <br>
        couleurs = {'FF0000':'rouge',
        <br>
                    'ED7F10':'orange',
        <br>
                    'FFFF00':'jaune',
        <br>
                    '00FF00':'vert',
        <br>
                    '0000FF':'bleu',
        <br>
                    '4B0082':'indigo',
        <br>
                    '660099':'violet'}
        <br>
        Les couleurs de l'arc-en-ciel sont :
        <br>

        <br>

        <br>
        {% for code, nom in couleurs.items %}
        <br>
        style="color:#{{ code }}">{{ nom }}
        <br>
        {% endfor %}
        <br>

        <br>
        Ce qui nous donne le HTML suivant :
        <br>

        <br>

        <br>
        style="color:#ED7F10">orange
        <br>
        style="color:#4B0082">indigo
        <br>
        style="color:#0000FF">bleu
        <br>
        style="color:#FFFF00">jaune
        <br>
        style="color:#660099">violet
        <br>
        style="color:#FF0000">rouge
        <br>
        style="color:#00FF00">vert
        <br>

        <br>
        Vous pouvez aussi réaliser n'importe quelle opération classique avec la variable générée par la boucle for (ici couleur) : une condition, utiliser une autre boucle, l'afficher, etc.
        <br>

        <br>

        <br>
        <h2>block:</h2>
        <br>
        Sur la quasi-totalité des sites web, une page est toujours composée de la même façon : un haut de page, un menu et un pied de page. Si vous copiez-collez le code de vos menus dans tous vos templates et qu'un jour vous souhaitez modifier un élément de votre menu, il vous faudra modifier tous vos templates ! Heureusement, le tag {% block %} nous permet d'éviter cette situation épineuse. En effet, il est possible de déclarer des blocs, qui seront définis dans un autre template, et réutilisables dans le template actuel. Dès lors, nous pouvons créer un fichier, appelé usuellement base.html, qui va définir la structure globale de la page, autrement dit son squelette.
        <br>

        <br>
        Tout d'abord ce fichier base.html , nous allons l'enregistrer dans le dossier templates/ du projet et non dans l'application. Souvenez-vous : tout ce qui est relatif au projet va dans un des dossiers de la liste TEMPLATE_DIRS . Pour ce cours c'est templates/. Maintenant, nous allons appelez ce fichier dans chacun des templates de notre blog.
        <br>

        <br>
        Pour ce faire, nous utilisons le tag {% extends %} (pour ceux qui ont déjà fait de la programmation objet, cela doit vous dire quelque chose ; cette méthode peut aussi être assimilée à include en PHP). Nous parlons alors d'héritage de templates. Nous prenons la base que nous surchargeons, afin d'obtenir un résultat dérivé :
        <br>

        <br>
        {% extends "base.html" %}
        <br>
        {% block title %}Ma page d'accueil{% endblock %}
        <br>
        {% block content %}
        <br>

        <br>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec rhoncus
        <br>
            massa non tortor. Vestibulum diam diam, posuere in viverra in,
        <br>
            ullamcorper et libero. Donec eget libero quis risus congue imperdiet ac
        <br>
            id lectus. Nam euismod cursus arcu, et consequat libero ullamcorper sit
        <br>
            amet.
        <br>

        <br>
        {% endblock %}
        <br>
        Dans cet exemple, nous avons défini deux blocs, title et content. Le tag extends va aller chercher dans le template donné en argument, ici base.html, et remplacer les blocs vides de ce dernier par les blocs de même nom définis dans le template appelé par la vue. Ainsi, title et content seront repris du template fils, mais nav sera le bloc nav défini dans base.html.
        <br>

        <br>
        <h2>Affichage d'une variable</h2>
        <br>

        <br>
        Comme nous l'avons déjà expliqué, la vue transmet au template les données destinées à l'utilisateur. Ces données correspondent à des variables classiques de la vue. Nous pouvons les afficher dans le template grâce à l'expression {{ }} qui prend à l'intérieur des accolades un argument (on pourrait assimiler cette expression à une fonction), le nom de la variable à afficher. Le nom des variables est également limité aux caractères alphanumériques et aux underscores.
        <br>

        <br>
        Bonjour {{ pseudo }}, nous sommes le {{ date }}.
        <br>
        Ici, nous considérons que la vue a transmis deux variables au template : pseudo et date. Ceux-ci seront affichés par le moteur de template. Si pseudo vaut « Jean » et date « 28 décembre », le moteur de templates affichera « Bonjour Jean, nous sommes le 28 décembre. ».
        <br>

        <br>
        Si jamais la variable n'est pas une chaîne de caractères, le moteur de templates utilisera la méthode __str__ de l'objet pour l'afficher. Par exemple, les listes seront affichés sous la forme ['élément 1', 'élément 2'…], comme si vous demandiez son affichage dans une console Python. Il est possible d'accéder aux attributs d'un objet comme en Python, en les juxtaposant avec un point. Plus tard, nos articles de blog seront représentés par des objets, avec des attributs titre, contenu, etc. Pour y accéder, la syntaxe sera la suivante :
        <br>

        <br>
        {# Nous supposons que notre vue a fourni un objet nommé article contenant les attributs titre, auteur et contenu #}
        <br>

        <br>
        Si jamais une variable n'existe pas, ou n'a pas été envoyée au template, la valeur qui sera affichée à sa place est celle définie par TEMPLATE_STRING_IF_INVALID dans votre settings.py, qui est une chaîne vide par défaut.
    </div>
</div>
{% endverbatim myblock %}
{% endblock %}

piscine_django/day04/ex02/templates/ex02/form_exercice.html
{% extends 'base.html' %}

{% block title %}Ex02 : Formulaire.{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="justify-content-center mt-5 mb-5">
            <h1 class="text-center mt-3 mb-3">Formulaire</h1>
            <form action="#" method="post">
                {% csrf_token %}
                <p class="text-center">{{ form.message }}</p>
                <p class="text-center"><input type="submit" value="Submit"></p>
            </form>
        </div>
        <div class="justify-content-center  mt-5 mb-5">
            <h1 class="text-center mt-3 mb-5">Historique des messages</h1>
            {% for message in messages %}
                <p class="text-center">{{ message }}</p>
                </br>
            {% endfor %}
        </div>
    </div>
{% endblock %}

piscine_django/day04/ex03/templates/ex03/tab_exercice.html
{% extends 'base.html' %}

{% block title %}Ex03 : Color_tab.{% endblock %}

{% block content %}
    <div class="container mt-5">
            <table class="container col-md-6" border="1px solid black">
                <thead class="justify-content-center">
                    <tr>
                        <th style="text-align:center">Rouge</th>
                        <th style="text-align:center">Vert</th>
                        <th style="text-align:center">Bleu</th>
                        <th style="text-align:center">Noir</th>
                    </tr>
                </thead>
                <tbody class="justify-content-center">
                    {% for color in colors %}
                    <tr>
                        <td style="width:80px;height:40px;background-color:rgba(255, 0, 0, {{ color }})"></td>
                        <td style="width:80px;height:40px;background-color:rgba(0, 255, 0, {{ color }})"></td>
                        <td style="width:80px;height:40px;background-color:rgba(0, 0, 255, {{ color }})"></td>
                        <td style="width:80px;height:40px;background-color:rgba(0, 0, 0, {{ color }})"></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
    </div>
{% endblock %}