piscine_django/day05/day05/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ex01/', include('ex01.urls')),
    path('ex03/', include('ex03.urls')),
    path('ex05/', include('ex05.urls')),
    path('admin/', admin.site.urls),
]

piscine_django/day05/ex01/urls.py
from django.urls import path
from . import views

app_name = 'ex01'
urlpatterns = [
    path('init/', views.init, name='init'),
]

piscine_django/day05/ex03/urls.py
from django.urls import path
from . import views

app_name = 'ex03'
urlpatterns = [
    path('init/', views.init, name='init'),
    path('populate/', views.populate, name='populate'),
    path('display/', views.display, name='display'),
]

piscine_django/day05/ex05/urls.py
from django.urls import path
from . import views

app_name = 'ex05'
urlpatterns = [
    path('init/', views.init, name='init'),
    path('populate/', views.populate, name='populate'),
    path('display/', views.display, name='display'),
    path('remove/', views.remove, name='remove'),
]

piscine_django/day05/day05/templates/day05/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html style="height: 80vh">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <title>
            {% block title %}
            {% endblock %}
        </title>
        {% block style %}
            {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'day04/style.css' %}"> {% endcomment %}
        {% endblock %}
    </head>
  
    <body class="h-100">
        <div class="text-center"> 
            {% comment %} <a href="{% url 'ex01:django_description' %}" style="text-decoration: none; color:black"> {% endcomment %}
            <h1>Piscine Django</a></h1>
        </div>
        {% include 'nav.html' %}
        {% block content %}
        {% endblock %}
    </body>
</html>

piscine_django/day05/day05/templates/day05/nav.html
<div id="navbar">
    <div class="container page-header sticky-top">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'ex01:init' %}">Ex01<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Ex03
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="{% url 'ex03:init' %}">Init table</a>
                      <a class="dropdown-item" href="{% url 'ex03:populate' %}">Populate table</a>
                      <a class="dropdown-item" href="{% url 'ex03:display' %}">Display table</a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Ex05
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="{% url 'ex05:init' %}">Init table</a>
                      <a class="dropdown-item" href="{% url 'ex05:populate' %}">Populate table</a>
                      <a class="dropdown-item" href="{% url 'ex05:display' %}">Display table</a>
                      <a class="dropdown-item" href="{% url 'ex05:remove' %}">Remove table</a>
                  </div>
                </li>
              </ul>
            </div>
          </nav>
    </div>
</div>